export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAIL = "ADD_POST_FAIL";

export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export const POSTS_LOADING = "POSTS_LOADING";
export const POSTS_LOADED = "POSTS_LOADED";

export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_ONE_SUCCESS = "REGISTER_ONE_SUCCESS";
export const REGISTER_TWO_SUCCESS = "REGISTER_TWO_SUCCESS";
export const REGISTER_ONE_FAIL = "REGISTER_ONE_FAIL";
export const REGISTER_TWO_FAIL = "REGISTER_TWO_FAIL";

export const DELETE_USER_ONE_SUCCESS = "DELETE_USER_ONE_SUCCESS";
export const DELETE_USER_TWO_SUCCESS = "DELETE_USER_TWO_SUCCESS";
export const DELETE_USER_ONE_FAIL = "DELETE_USER_ONE_FAIL";
export const DELETE_USER_TWO_FAIL = "DELETE_USER_TWO_FAIL";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const SERVER_ROOT_URL = "http://localhost:5000";

export const GET_CONFIG_SUCCESS = "GET_CONFIG_SUCCESS";
export const GET_CONFIG_FAIL = "GET_CONFIG_FAIL";
